{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "serviceops.fullname" . }}
  labels: {{- include "serviceops.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "serviceops.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - {port: 8080, protocol: TCP}
  egress:
    - ports:
        - {port: 53, protocol: UDP}
        - {port: 53, protocol: TCP}
    - ports:
        - {port: 5432, protocol: TCP}
        - {port: 389, protocol: TCP}
        - {port: 636, protocol: TCP}
        - {port: 443, protocol: TCP}
{{- end }}
