{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "serviceops.fullname" . }}
  labels: {{- include "serviceops.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels: {{- include "serviceops.selectorLabels" . | nindent 6 }}
{{- end }}
