{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "serviceops.fullname" . }}-secrets
  labels: {{- include "serviceops.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "secret.secretKey is required" .Values.secret.secretKey | quote }}
  ADMIN_PASSWORD: {{ required "secret.adminPassword is required" .Values.secret.adminPassword | quote }}
  DATABASE_URL: {{ if eq .Values.database.mode "bundled" }}{{ printf "postgresql+psycopg://%s:%s@%s-postgresql:5432/%s" .Values.database.bundled.username .Values.database.bundled.password (include "serviceops.fullname" .) .Values.database.bundled.database | quote }}{{ else }}{{ required "secret.databaseUrl is required for external database mode" .Values.secret.databaseUrl | quote }}{{ end }}
  LDAP_BIND_PASSWORD: {{ .Values.secret.ldapBindPassword | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.keycloakClientSecret | quote }}
{{- end }}
