{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "serviceops.fullname" . }}
  labels: {{- include "serviceops.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "serviceops.labels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.observability.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout }}
{{- end }}
