"""Generate serviceops_core/interface_values.py: the fixed interface values
(workflow states, statuses, priorities, roles, record kinds, ...) that pages
display through tr_value().

Values are harvested from source structure rather than typed by hand:
enum-like constants, transition tables, model column defaults, and literals
compared with or assigned to enum-like attributes. Free-text record content is
never harvested. Run with --check in tests to keep the registry current.
"""
import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "serviceops_core" / "interface_values.py"
ENUM_ATTRIBUTES = {"state", "status", "stage", "priority", "impact", "urgency", "risk", "severity", "phase", "role",
                   "effective_role", "kind", "decision", "outcome", "lifecycle_state", "operational_status",
                   "compensation_state", "relationship_role", "approval_status", "health", "last_status",
                   "last_run_status", "client_kind", "agreement_type"}
ENUM_CONSTANT = re.compile(r"(STATES?|STATUSES|TRANSITIONS|PRIORITIES|ROLES|ORDER|STAGES|KINDS|LEVELS|DECISIONS|OUTCOMES|IMPACTS?|URGENC(Y|IES)|RISKS?|SEVERITIES|RELATIONSHIP_TYPES|AGREEMENT_TYPES|ROLE_RANK|CATEGORIES)$")
DISPLAY_KEYS = {"label", "description", "help", "placeholder", "empty_text", "hint", "title", "summary", "help_text"}
DISPLAY_TEXT = re.compile(r"(?=.*[A-Za-z]{2})[A-Z\"'(].*|.* .*")
# Model-facing text (prompts, tool schemas) is not interface text.
EXCLUDED_DIRECTORIES = {"ai"}
TITLE_VALUE = re.compile(r"[A-Z][A-Za-z]*(?:[ -][A-Za-z]+){0,4}")
LOWER_WORD = re.compile(r"[a-z]{3,}")
HEADER = '''"""Fixed interface values shown through tr_value(): generated by
tools/i18n_interface_values.py from the source; do not edit by hand."""
from serviceops_core.localization import translatable

VALUES = (
'''


def harvest(root=ROOT):
    values = set()
    lowercase = set()
    paths = [root / "app.py", root / "serviceops_models.py", *sorted((root / "serviceops_core").rglob("*.py"))]

    def add(value, allow_lower=False):
        if not isinstance(value, str):
            return
        if TITLE_VALUE.fullmatch(value) and 2 <= len(value) <= 40 and not value.isupper():
            values.add(value)
        elif allow_lower and LOWER_WORD.fullmatch(value):
            lowercase.add(value)

    def constants(node, allow_lower=False):
        for child in ast.walk(node):
            if isinstance(child, ast.Constant):
                add(child.value, allow_lower)

    def attribute_name(node):
        if isinstance(node, ast.Attribute):
            return node.attr
        if isinstance(node, ast.Name):
            return node.id
        return None

    def add_display(value):
        if isinstance(value, str) and DISPLAY_TEXT.fullmatch(value) and "${" not in value and len(value) <= 600:
            values.add(value)

    for path in paths:
        if path.name in {"interface_values.py", "localization.py"} or EXCLUDED_DIRECTORIES & set(path.relative_to(root).parts[:-1]):
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Dict):
                for key, value in zip(node.keys, node.values):
                    if isinstance(key, ast.Constant) and key.value in DISPLAY_KEYS and isinstance(value, ast.Constant):
                        add_display(value.value)
            if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id.lower().endswith(("_meta", "_labels"))
                                                    for target in node.targets) and isinstance(node.value, ast.Dict):
                for value in node.value.values:
                    for child in ast.walk(value):
                        if isinstance(child, ast.Constant):
                            add_display(child.value)
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    name = attribute_name(target)
                    if isinstance(target, ast.Name) and ENUM_CONSTANT.search(target.id):
                        constants(node.value, allow_lower=target.id in {"ROLE_RANK", "KNOWN_ROLES"})
                    elif name in ENUM_ATTRIBUTES and isinstance(node.value, ast.Constant):
                        add(node.value.value, allow_lower=name in {"role", "kind", "status"})
                    if isinstance(target, ast.Name) and name in ENUM_ATTRIBUTES and isinstance(node.value, ast.Call):
                        for keyword in node.value.keywords:
                            if keyword.arg == "default":
                                add(getattr(keyword.value, "value", None), allow_lower=name in {"role", "kind", "status"})
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and ENUM_CONSTANT.search(node.target.id) and node.value:
                constants(node.value)
            elif isinstance(node, ast.Compare):
                name = attribute_name(node.left)
                if name in ENUM_ATTRIBUTES:
                    for comparator in node.comparators:
                        constants(comparator, allow_lower=name in {"role", "kind", "status"})
            elif isinstance(node, ast.Call):
                for keyword in node.keywords:
                    if keyword.arg in ENUM_ATTRIBUTES and isinstance(keyword.value, ast.Constant):
                        add(keyword.value.value, allow_lower=keyword.arg in {"role", "kind", "status"})
    # Settings labels include f-strings expanded at import (proxy pairs).
    sys.path.insert(0, str(root))
    from serviceops_core import config_schema
    for definitions in config_schema.SETTING_DEFINITIONS.values():
        for definition in definitions:
            if definition.get("key") == "DEFAULT_LANGUAGE":
                add_display(definition.get("label"))
                continue
            for key in ("label", "help", "placeholder"):
                add_display(definition.get(key))
            for label in (definition.get("choice_labels") or {}).values():
                add_display(label)
    # Pages show lowercase codes through |capitalize or |title as well.
    for value in lowercase:
        values.add(value)
        values.add(value.capitalize())
    return sorted(values)


def render(values):
    return HEADER + "".join(f"    translatable({value!r}),\n" for value in values) + ")\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(harvest())
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            print("serviceops_core/interface_values.py is out of date: run tools/i18n_interface_values.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print(f"{content.count('translatable(') - 1} values")
    return 0


if __name__ == "__main__":
    sys.exit(main())
